POST http://localhost:8082/start-trip
Content-Type: application/json

{
  "orderID": "2",
  "clientNumber": "79181228555",
  "driverID": "3"
}

###

POST http://localhost:8082/end-trip
Content-Type: application/json

{
  "orderID": "2",
  "clientNumber": "79181228555",
  "driverID": "3"
}

###